name: iot_water_meter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.2
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  go_router: ^8.2.0
  google_fonts: ^5.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  ndialog: ^4.3.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.1
  syncfusion_flutter_charts: ^22.1.37

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
